import type { TourStep } from '@/components/tour/tour-provider';

export const tourSteps: Omit<TourStep, 'content'>[] = [
  {
    id: 'step-1-welcome',
    target: '#hero',
    title: '👋 Welcome to AI Jobs!',
    placement: 'bottom',
    moduleName: 'Welcome Message',
    featureDescription: 'A friendly welcome message for the user, introducing them to the AI Jobs Dashboard and prompting them to start the tour.',
  },
  {
    id: 'step-2-navbar',
    target: '#navbar',
    title: '🧭 Navigation Bar',
    placement: 'bottom',
    moduleName: 'Navbar',
    featureDescription: 'The main navigation bar at the top of the page. It contains the logo, primary navigation links (Dashboard, Jobs, Analytics, Settings), and the user profile menu.',
  },
  {
    id: 'step-3-profile',
    target: '#profile-menu',
    title: '👤 Profile Menu',
    placement: 'bottom',
    moduleName: 'Profile Menu',
    featureDescription: 'The user profile menu, which allows access to account settings, billing information, and the logout option.',
  },
  {
    id: 'step-4-progress',
    target: '#progress-tracker',
    title: '📊 Progress Tracker',
    placement: 'left',
    moduleName: 'Progress Tracker',
    featureDescription: 'A widget that shows the user\'s progress, such as profile completion and the number of job applications sent. It helps motivate users to complete their tasks.',
  },
  {
    id: 'step-5-features',
    target: '#feature-cards',
    title: '✨ Your AI Toolkit',
    placement: 'bottom',
    moduleName: 'Feature Cards Section',
    featureDescription: 'An introduction to the main AI-powered features available on the dashboard. These tools are designed to help the user in their job search.',
  },
  {
    id: 'step-6-resume-card',
    target: '#resume-builder-card',
    title: '📄 AI Resume Builder',
    placement: 'bottom',
    moduleName: 'AI Resume Builder Card',
    featureDescription: 'This feature helps users create a professional, optimized resume using AI. It suggests improvements and tailors the resume to specific job descriptions.',
  },
  {
    id: 'step-7-analytics',
    target: '#analytics',
    title: '📈 Analytics Overview',
    placement: 'top',
    moduleName: 'Analytics Section',
    featureDescription: 'An introduction to the analytics section, which provides insights into the user\'s job application performance and resume strength over time.',
  },
  {
    id: 'step-8-bar-chart',
    target: '#bar-chart-card',
    title: '📥 Applications Chart',
    placement: 'top',
    moduleName: 'Applications Per Month Chart',
    featureDescription: 'This bar chart visualizes the number of job applications the user has sent each month, allowing them to track their activity.',
  },
  {
    id: 'step-9-settings',
    target: '#settings',
    title: '⚙️ Settings',
    placement: 'top',
    moduleName: 'Settings Section',
    featureDescription: 'The settings area where users can manage their account information, such as name and email, and other preferences.',
  },
  {
    id: 'step-10-finish',
    target: '',
    title: '🎉 You\'re All Set!',
    placement: 'center',
    moduleName: 'Tour Completion',
    featureDescription: 'A final congratulatory message marking the end of the tour. It encourages the user to start using the dashboard and reminds them they can replay the tour anytime.',
  },
];
