import type { TourStep } from '@/components/tour/tour-provider';

export const tourSteps: Omit<TourStep, 'content'>[] = [
  {
    id: 'step-1-welcome',
    target: '#hero',
    title: '👋 Welcome to AI Jobs!',
    placement: 'bottom',
    moduleName: 'Welcome Message',
    featureDescription: 'A brief welcome to the AI Jobs Dashboard.',
  },
  {
    id: 'step-2-navbar',
    target: '#navbar',
    title: '🧭 Navigation Bar',
    placement: 'bottom',
    moduleName: 'Navbar',
    featureDescription: 'The main navigation with links to key sections.',
  },
  {
    id: 'step-3-profile',
    target: '#profile-menu',
    title: '👤 Profile Menu',
    placement: 'bottom',
    moduleName: 'Profile Menu',
    featureDescription: 'Access your account settings, billing, and logout.',
  },
  {
    id: 'step-4-progress',
    target: '#progress-tracker',
    title: '📊 Progress Tracker',
    placement: 'left',
    moduleName: 'Progress Tracker',
    featureDescription: 'Track your profile completion and applications sent.',
  },
  {
    id: 'step-5-features',
    target: '#feature-cards',
    title: '✨ Your AI Toolkit',
    placement: 'bottom',
    moduleName: 'Feature Cards Section',
    featureDescription: 'An overview of the AI-powered tools available to you.',
  },
  {
    id: 'step-6-resume-card',
    target: '#resume-builder-card',
    title: '📄 AI Resume Builder',
    placement: 'bottom',
    moduleName: 'AI Resume Builder Card',
    featureDescription: 'Create a professional resume with help from AI.',
  },
  {
    id: 'step-7-analytics',
    target: '#analytics',
    title: '📈 Analytics Overview',
    placement: 'top',
    moduleName: 'Analytics Section',
    featureDescription: 'Insights into your job application performance.',
  },
  {
    id: 'step-8-bar-chart',
    target: '#bar-chart-card',
    title: '📥 Applications Chart',
    placement: 'top',
    moduleName: 'Applications Per Month Chart',
    featureDescription: 'Visualize your monthly job application activity.',
  },
  {
    id: 'step-9-settings',
    target: '#settings',
    title: '⚙️ Settings',
    placement: 'top',
    moduleName: 'Settings Section',
    featureDescription: 'Manage your account information and preferences.',
  },
  {
    id: 'step-10-finish',
    target: '',
    title: '🎉 You\'re All Set!',
    placement: 'center',
    moduleName: 'Tour Completion',
    featureDescription: 'You have completed the tour! Feel free to explore.',
  },
];
