import type { TourStep } from '@/components/tour/tour-provider';

export const tourSteps: TourStep[] = [
  {
    id: 'step-1-welcome',
    target: '#hero',
    title: '👋 Welcome to TourGuideAI!',
    placement: 'bottom',
    content: 'Let\'s take a tour of your AI-powered job-seeking dashboard.',
    path: '/',
  },
  {
    id: 'step-2-features',
    target: '#feature-cards',
    title: '✨ Your AI Toolkit',
    placement: 'bottom',
    content: 'Here are the powerful AI tools to help you in your job search.',
    path: '/',
  },
  {
    id: 'step-3-progress',
    target: '#progress-tracker',
    title: '📊 Progress Tracker',
    placement: 'left',
    content: 'Keep an eye on your profile completion and application stats here.',
    path: '/',
  },
  {
    id: 'step-4-tools',
    target: '#tools-section',
    title: '🛠️ Quick Tools',
    placement: 'left',
    content: 'Instantly access your resume builder and other core tools.',
    path: '/',
  },
  {
    id: 'step-4a-nav-to-jobs',
    target: '',
    title: '🚀 Moving to Jobs',
    placement: 'center',
    content: 'Next, let\'s check out the recommended jobs page.',
    path: '/', 
  },
  {
    id: 'step-5-jobs-page',
    target: '#jobs-section',
    title: '💼 Recommended Jobs',
    placement: 'top',
    content: 'Here you can discover job opportunities tailored just for you.',
    path: '/jobs',
  },
  {
    id: 'step-6-job-card',
    target: '#job-card-1',
    title: '📄 Job Card',
    placement: 'bottom',
    content: 'Review job details and apply with a single click using AI.',
    path: '/jobs',
  },
  {
    id: 'step-6a-nav-to-analytics',
    target: '',
    title: '🚀 Moving to Analytics',
    placement: 'center',
    content: 'Let\'s head over to the analytics page to see your progress.',
    path: '/jobs', 
  },
  {
    id: 'step-7-analytics-page',
    target: '#analytics',
    title: '📈 Analytics Overview',
    placement: 'top',
    content: 'Get insights into your job application performance and resume scores.',
    path: '/analytics',
  },
  {
    id: 'step-8-bar-chart',
    target: '#bar-chart-card',
    title: '📥 Applications Chart',
    placement: 'top',
    content: 'Visualize your monthly job application activity to track your progress.',
    path: '/analytics',
  },
  {
    id: 'step-8a-nav-to-settings',
    target: '',
    title: '🚀 Moving to Settings',
    placement: 'center',
    content: 'Almost done! Let\'s go to the settings page.',
    path: '/analytics',
  },
  {
    id: 'step-9-settings-page',
    target: '#settings',
    title: '⚙️ Settings',
    placement: 'top',
    content: 'Here you can manage your account information.',
    path: '/settings',
  },
  {
    id: 'step-10-finish',
    target: '',
    title: "🎉 You're All Set!",
    placement: 'center',
    content: 'You have completed the tour! Feel free to explore and good luck with your job hunt!',
    path: '/settings',
  },
];
